apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: linkding-ingress
  namespace: linkding
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  rules:
  - host: linkding.home.lab
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: linkding-service
            port:
              number: 9090
